### ISSUE TITLE
我在执行服务器消耗的时候队列是执行了。但是没有输出。

### ISSUE THREAD

**Issue by kevin19a** [coolseven/notes#13]
问题如上
有提示processed：application\index\job\hello
但是没有我想要的输出
redis过一会看。。被移除队列了。。。

**Comment by wangqiang886** [comment]
我也遇到了这样问题, 请问你解决了吗?

**Comment by wangqiang886** [comment]
- 经过今天一系列的实验, 发现两个服务监听的任务名称一样, 然后两个程序都能处理这个任务, 所以导致任务不知道被那个程序处理了

1. 解决方式, 将两个任务放入不同的db, 为了保险吧任务队列名称也换成不一样的, 结果一切都正常了
