### ISSUE TITLE
我这个为什么执行了队列但是没有打印信息

### ISSUE THREAD

**Issue by veeki** [coolseven/notes#15]
![image](https://user-images.githubusercontent.com/3205643/48813213-e346fb00-ed70-11e8-9749-7e96eb29e4ac.png)
![image](https://user-images.githubusercontent.com/3205643/48813220-e8a44580-ed70-11e8-8338-7a2561f6ea3f.png)

显示了  
![image](https://user-images.githubusercontent.com/3205643/48813279-23a67900-ed71-11e8-99be-6fbeb683978d.png)
进程是有任务的   但是显示不了打印数据  似乎是没有执行

**Comment by Caesar0220** [comment]
你要浏览器先运行/index/job/actionWithHelloJob,push到redis队列中去，然后在命令行里运行php think queue:work --queue helloJobQueue就可以了。
