### ISSUE TITLE
任务的开始执行的时刻 + expire > 当前时刻

### ISSUE THREAD

**Issue by RoshanGH** [coolseven/notes#18]
任务的开始执行的时刻 + expire > 当前时刻  这个不应该是 小于吗  还是我理解错了？

**Comment by coolseven** [comment]
> 任务的开始执行的时刻 + expire > 当前时刻

expire 可以理解为任务允许执行的最长时间
如果任务开始执行之后, 经过了 expire 时间之后还在运行 , 而没有没删除, 那么表示任务已过期

所以 任务的开始执行的时刻 + expire > 当前时刻  表示该任务已过期
