### ISSUE TITLE
请问怎么pull你的代码呢？

### ISSUE THREAD

**Issue by huluhua** [coolseven/notes#3]
我也push成功，但也是不执行任务

**Comment by coolseven** [comment]
@huluhua 你好,不太明白你的问题,可以描述一下具体的重现方法吗?

**Comment by huluhua** [comment]
队列push成功,但是切换到命令行输入命令看不到输出，代码没有执行成功

**Comment by coolseven** [comment]
@huluhua 你好,你可以试试把你本地的代码提交到 github上,这样的话方便大家定位和调试问题.

**Comment by huluhua** [comment]
你的代码能否给我一份呢

**Comment by huluhua** [comment]
你的代码pull不下来

**Comment by huluhua** [comment]
或是请教一下你，我这边的代码可以发给你看看，谢谢！

**Comment by huluhua** [comment]
我的这个项目是个性化批量发送短信，先将要发送的手机号码和短信内容组织好，存入数组，然后通过curl调用接口进行发送，接口端接收代码和主要逻辑代如下：
public function batchSend($jobDatas)
    {
        if (!is_array($jobDatas))
        {
            fail_result("数据错误");
        }
        foreach ($jobDatas as $key=>$jobData)
        {

            $jobHandlerClassName  = 'app\\base\\job\\SmsJob@fire';
            $jobQueueName  	  = "smsJobQueue";//队列名称
            $isPushed = Queue::push( $jobHandlerClassName , $jobData , $jobQueueName );
            $data_s['id']=$jobData['id'];
            if( $isPushed !== false ){
                $data_s['success']="发送中";
            }else{
                $data_s['success']="提交失败";
            }
            Db::name('msglogs_detail')->update($data_s);
            /*$obj=new \app\base\job\SmsJob();
            $obj->batchSend($jobData);*/
        }
    }

job代码：
namespace app\base\job;
use app\base\controller\Sms;
use think\Queue\Job;
class SmsJob
{
    public function fire(Job $job,$data){

        $isJobDone = $this->batchSend($data);
        if ($isJobDone) {
            print("<info>SMS Job has been done and deleted"."</info>\n");
            $job->delete();
        }else{
            if ($job->attempts() > 3) {
                print("<warn>Sms Job has been retried more than 3 times!"."</warn>\n");
                $job->delete();
                print("<info>Sms Job will be availabe again after 2s."."</info>\n");
                $job->release(2); //$delay为延迟时间，表示该任务延迟2秒后再执行
            }
        }
    }
    /**
     * 批量发送短信
     * @param array|mixed    $data为一个数组，以","分隔的手机号码和以&号分隔的
     * @return boolean                 任务执行的结果
     */
    public function batchSend($data)
    {
        //print("<info>Hello Job Started. job Data is: ".var_export($data,true)."</info> \n");
        //print("<info>Hello Job is Fired at " . date('Y-m-d H:i:s') ."</info> \n");
        //print("<info>Hello Job is Done!"."</info> \n");
        $msgid=$data['id'];
        $mobile=$data['receive'];
        $msgcontent=$data['content'];
        $sms=new Sms();
        $result=$sms->sendSms($mobile,$msgcontent,"");
        $status="失败";
        if ($result['errorno']==1) //发送成功
        {
            $status="成功";
        }
        $data['id']=$msgid;
        $data['success']=$status;
        Db::name('msglogs_detail')->update($data);
    }
}

**Comment by coolseven** [comment]
@huluhua 我换了一家公司，原来的 think-queue 相关的代码已经看不到了。。。
我在本地重新搭建一个 think-queue 的环境试试看吧。
如果可以的话，能否把你项目的 composer.json 发在这里？ 我根据你项目的 think-queue 版本来尝试一下复原。

**Comment by huluhua** [comment]
@coolseven  你好，能不能加个QQ，请教一下你，我是对着你的笔记来写的代码，但是无法跑通，我学PHP的时间不是太长

**Comment by coolseven** [comment]
@huluhua，你好，我的QQ号是 1059057024

**Comment by coolseven** [comment]
已解决，语法问题。
