### ISSUE TITLE
现在出2.0了，作者有空更新么？

### ISSUE THREAD

**Issue by Skull-Li** [coolseven/notes#6]
对队列了解不是比较透彻
官方介绍稀少
对于队列中的监控，执行情况，调度过程等缺少比较易懂的介绍
2.0是thinkphp 5.1用的和5.0->1.x版本估计略有偏差
不知作者是否有空更新下对2.x相关的介绍与完善？

感谢，看了作者的笔记认知提高了不少。

**Comment by coolseven** [comment]
@Skull-Li 好的，谢谢提醒，确实有一些地方需要重新组织一下语言。预计在3月中旬开始更新。

**Comment by Array-Huang** [comment]
作者的笔记那么好，可以联系一下think-queue作者把你的笔记作为官方文档挂上去呀
