### ISSUE TITLE
执行php think queue:work --daemon --queue helloJobQueue没有结果，配置目录没有问题

### ISSUE THREAD

**Issue by xiaochengfu** [coolseven/notes#8]
你好，我按你写的配置了，控制器执行的时候，直接就把消费者的打印信息，输出出来了，而消费者端起的命令服务，却没有一点反应，实在是找不到问题，能帮我看一下吗？

**Comment by lihaotian0607** [comment]
同问

**Comment by lihaotian0607** [comment]
楼书解决了吗?

**Comment by xiaochengfu** [comment]
木有啊，你解决了吗？

**Comment by schafferYao** [comment]
@xiaochengfu @lihaotian0607 命名空间的问题
所有命名空间用app开头
命名空间是app\job的
这个文档上写的application。所以导致的问题

**Comment by seizeMiss** [comment]
跟tp的版本有关系吗，我已经改成app了，但是还是不行的

**Comment by coolseven** [comment]
已更新文档, 与 think-queue 的 2.0 版本一致

**Comment by fsyphp** [comment]
怎样提前删除队列中的消息
